### ISSUE TITLE
FullNat

### ISSUE THREAD

**Issue by zjx-caicloud** [caicloud/loadbalancer-controller#47]
![fullnat](http://img.blog.csdn.net/20150728051833972?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQv/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

Under the fullnat mode, LVS replaces the source ip and port with its ip and port, replaces des ip and port with RS's ip and port. In order not to lose client ip, fullnat add an option to TCP package to store client ip. When realserver gets the package, it gets the client ip through toa module of kernel. It seems to meet the requirement? @zoumo 

I will set up fullnat with kubernetes to test whether it can work in a couple of days.

**Comment by kdada** [comment]
It's workable in theory. But real server can't get real src ip (See taobao/toa).

**Comment by zjx-caicloud** [comment]
It puzzles me... Do you mean ``The fullnat alone can't ensure that real servers get the real ip, but if we do what just taobao/toa does, real servers can get the real src ip?``

**Comment by kdada** [comment]
I means the workflow is workable. But the main concern is how to get real source ip in real server.

FYI:
1. For TCP, toa module can help you to get source ip from TCP packets. You just need to install it to kernels of real servers.
2. For UDP, https://github.com/yubo/ip_vs_ca may help you.

**Comment by zjx-caicloud** [comment]
Got it. I will try on it.

**Comment by zoumo** [comment]
:-D
